### ISSUE TITLE
Invalid formatted test suite result. Exception when opening JUnit xml file in Eclipse

### ISSUE THREAD

**Issue by gw4e** [GraphWalker/graphwalker-project#142]
The XMLReportGenerator creates a TEST-GraphWalker-........xml file at the end of a test execution.
The file is missing the **_name_**  attribute in the **_testsuites_** tag.
This leads to an exception when opening the file in the Eclipse JUnit view.

org.eclipse.core.runtime.AssertionFailedException: null argument:
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:85)
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:73)
	at org.eclipse.jdt.internal.junit.model.TestRunSession.<init>(TestRunSession.java:148)
	at org.eclipse.jdt.internal.junit.model.TestRunHandler.startElement(TestRunHandler.java:125)

**Comment by KristianKarl** [comment]
Good catch,and thanks for the PR, which I have merged.
