### ISSUE TITLE
Tutorial gives 'java.lang.reflect.InvocationTargetException: No start context found" exception

### ISSUE THREAD

**Issue by HansvdLaan** [GraphWalker/graphwalker-project#185]
I did this tutorial together with one of my peers on his computer: http://graphwalker.github.io/create_a_test_using_maven/. However, after sharing the project on GitHub and trying it out on my own computer I get the following error. "java.lang.reflect.InvocationTargetException: No start context found" exception. This is weird since the project hasn't changed. The only difference is that he runs Linux and I run Windows.

`org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.graphwalker:graphwalker-maven-plugin:3.4.2:test (default-cli) on project myProject: Execution default-cli of goal org.graphwalker:graphwalker-maven-plugin:3.4.2:test failed: java.lang.reflect.InvocationTargetException
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.graphwalker:graphwalker-maven-plugin:3.4.2:test failed: java.lang.reflect.InvocationTargetException
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.graphwalker.java.test.Reflections.newInstance(Reflections.java:68)
	at org.graphwalker.java.test.Reflector.createExecutor(Reflector.java:106)
	at org.graphwalker.java.test.Reflector.<init>(Reflector.java:100)
	at org.graphwalker.maven.plugin.TestMojo.execute(TestMojo.java:151)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 22 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.graphwalker.java.test.Reflections.newInstance(Reflections.java:65)
	... 26 more
Caused by: org.graphwalker.core.machine.MachineException: No start context found
	at org.graphwalker.core.machine.SimpleMachine.chooseStartContext(SimpleMachine.java:96)
	at org.graphwalker.core.machine.SimpleMachine.<init>(SimpleMachine.java:76)
	at org.graphwalker.java.test.TestExecutor.createMachine(TestExecutor.java:170)
	at org.graphwalker.java.test.TestExecutor.<init>(TestExecutor.java:93)
	... 31 more`

**Comment by KristianKarl** [comment]
Hi,
Recently, there was a user with a similar problem on windows, [New with graphwalker - SmallTest Example/ Pet Clinic Example](https://groups.google.com/forum/#!searchin/graphwalker/No$20start$20context$20found%7Csort:date/graphwalker/lTJczFqhJMM/HVMC4sSsCAAJ). 

I'm not quite sure why this happens occasionally, but it seems to be an environment problem, rather than a graphwalker specific problem.

Have you tried `mvn clean` before retrying?

If you could share the project on GitHub with us, I could certainly have a look. Also, please share how you run the test, like the full command line.

**Comment by HansvdLaan** [comment]
Yes, I have tried mvn clean.

We have copied the project to this repository: https://github.com/Charrey/GraphWalkerBug. I run the command "mvn graphwalker:test" with cmd from the GraphWalkerBug directory. We both use Intellij as our IDE, running the command from the Intellij Maven Command Line gives the same result.

**Comment by KristianKarl** [comment]
Your test works for me, on both Linux and Windows.

The previous user of graphwalker experience this problem, thought that it might have a relation to the fact the his username contained white space - does your windows user name contain spaces?

If you run `mvn -version` what do you get?

**Comment by HansvdLaan** [comment]
Sorry for the late answer, I was quite busy with my coursework the last couple of days.

If I run `maven - version` I get the following:

`Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: C:\Program Files\JetBrains\IntelliJ IDEA 2017.1.3\plugins\maven\lib\maven3
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_65\jre
Default locale: nl_NL, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"
`

My username doesn't contain any white space. However, I do think the error still has something to do with the file path containing white spaces. I tried putting the project into a different directory so the path wouldn't contain any and it worked like a charm.

**Comment by nilols** [comment]
I can recreate this issue on MacOS, using spaces in the path to the project, I will look into this due to that it comes up from time to time.

**Comment by nilols** [comment]
I have found the problem, the issue is that the classloader will url encode the spaces, which in turn will make a File.exist check fail and thus filtered away. I wrote the code back in 2014 so I don't remember why I filter the urls, but I can create a PR that fixes the check and later on figure out why we even filter non existing urls.
