### ISSUE TITLE
core: test fails when run under openjdk8

### ISSUE THREAD

**Issue by KristianKarl** [GraphWalker/graphwalker-project#7]
Following error is caught:
```java
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
	at org.graphwalker.core.machine.AccessModelTest.read(AccessModelTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

Following patch is a fix for that. But how to solve it for other versions of jdk?
```sh
diff --git a/graphwalker-core/src/test/java/org/graphwalker/core/machine/AccessModelTest.java b/graphwalker-core/src/test/java/org/graphwalker/core/machine/AccessModelTest.java
index d3d3fdd..e6b7093 100644
--- a/graphwalker-core/src/test/java/org/graphwalker/core/machine/AccessModelTest.java
+++ b/graphwalker-core/src/test/java/org/graphwalker/core/machine/AccessModelTest.java
@@ -19,7 +19,7 @@ public class AccessModelTest {
     @Test
     public void read() {
         ExecutionContext context = createContext();
-        Assert.assertThat((Double)context.getAttribute("x"), is(1.0));
+        Assert.assertThat((Integer)context.getAttribute("x"), is(1));
     }
 
     @Test
```

**Comment by nilols** [comment]
Should be fixed in master now

**Comment by KristianKarl** [comment]
Yup, works for openjdk8 now.
